serverAddr = "8.217.131.234"
serverPort = 7000
auth.token = "402755219d6f2cd1ee27ff1eb23210be"
loginFailExit = false

[[proxies]]
name = "pi_31400"
type = "tcp"
localIP = "127.0.0.1"
localPort = 31400
remotePort = 31400

[[proxies]]
name = "pi_31401"
type = "tcp"
localIP = "127.0.0.1"
localPort = 31401
remotePort = 31401

[[proxies]]
name = "pi_31402"
type = "tcp"
localIP = "127.0.0.1"
localPort = 31402
remotePort = 31402

[[proxies]]
name = "pi_31403"
type = "tcp"
localIP = "127.0.0.1"
localPort = 31403
remotePort = 31403

[[proxies]]
name = "pi_31404"
type = "tcp"
localIP = "127.0.0.1"
localPort = 31404
remotePort = 31404

[[proxies]]
name = "pi_31405"
type = "tcp"
localIP = "127.0.0.1"
localPort = 31405
remotePort = 31405

[[proxies]]
name = "pi_31406"
type = "tcp"
localIP = "127.0.0.1"
localPort = 31406
remotePort = 31406

[[proxies]]
name = "pi_31407"
type = "tcp"
localIP = "127.0.0.1"
localPort = 31407
remotePort = 31407

[[proxies]]
name = "pi_31408"
type = "tcp"
localIP = "127.0.0.1"
localPort = 31408
remotePort = 31408

[[proxies]]
name = "pi_31409"
type = "tcp"
localIP = "127.0.0.1"
localPort = 31409
remotePort = 31409

